---
name: Continuous integration
on:
  - push
jobs:
  ci:
    name: Continuous Integration
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - ubuntu-latest
        node-version:
          - "18.14"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Linter
        uses: borales/actions-yarn@v4
        with:
          cmd: lint:qa
      - name: Type check
        uses: borales/actions-yarn@v4
        with:
          cmd: tsc
